version: "3.6"
services:
  cms:
    image: craftcms/nginx:8.0-dev
    container_name: stratus-craft-plugin
    ports:
      - ${WEB_SERVER_PORT:-8080}:8080
    volumes:
      - ./_cms:/app:cached
      - ./:/plugin:cached
    links:
      - mysql:mysql

  mysql:
    image: mysql/mysql-server:5.6
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=craft
      - MYSQL_USER=craft
      - MYSQL_PASSWORD=secret
    ports:
      - ${MYSQL_PORT:-33060}:3306
    volumes:
      - ./_db:/var/lib/mysql

  cronjobs:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cronjobs.ini:/etc/ofelia/config.ini

networks:
  default:
    name: stratus_stratus
